### ISSUE TITLE
[zf2] Help with zfc-rbac using JmlRbacZdb

### ISSUE THREAD

**Issue by mario16** [jmleroux/JmlRbacZdb#1]
I was reading this issue: https://github.com/ZF-Commons/zfc-rbac/issues/58
because I have a similar problem, I can not use doctrine so I am trying to implement with Zend Db. 
I imported your module 'JmlRbacZdb' to my project.
Now I define an input in the 'zfc_rbac.global' file like 

'role_provider' => array(
            'ZfcRbac\Role\ObjectRepositoryRoleProvider' => array(
                'object_repository'  => 'JmlRbacZdb\Provider\AdjacencyList\Role',
                'role_name_property' => 'name'
            )
        ),

But the server continues throwing an exception:
"Fatal error: Uncaught exception 'Zend\ServiceManager\Exception\ServiceNotFoundException' with message 'Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for JmlRbacZdb\Provider\AdjacencyList\Role\ZendDb'
"
zfc-rbac version -> composer.json -> "zf-commons/zfc-rbac": "~2.0"

**Comment by jmleroux** [comment]
This module was written for 0.2 branch.
I will work on it for ZfcRbac master branch

**Comment by jmleroux** [comment]
I made a quick example application for ZfcRbac.
You can check usage of ZendDb providers with this tag : https://github.com/jmleroux/zfc-rbac-application/tree/release-zend-db-0.2.0

**Comment by jmleroux** [comment]
Closing because this module is not ready for ZfcRbac > 0.2

**Comment by jmleroux** [comment]
I updated the module for ZfcRbac 2.x.
You can take a look at this example : https://github.com/jmleroux/zfc-rbac-application/tree/release-zend-db-2.0
Feel free to test it and make a feedback.
